pins:
  heat_pin: 17
  cool_pin: 27
  fan_pin: 22
  active_low: true

control:
  mode: auto
  setpoint_c: 22.0
  deadband_c: 0.5
  compressor_min_off_s: 300
  fan_lead_s: 5
  fan_lag_s: 15

sensor:
  kind: mock
  ds18b20_id: null
